HelloDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('blog.urls')),
    path('api-auth/', include('rest_framework.urls'))
]

handler404 = 'blog.views.handler404'

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('posts/<int:id>/', views.post_detail, name='post_detail'),
    path('posts/<int:id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:id>/publish/', views.post_publish, name='post_publish'),
    path('post/add/', views.post_add, name='post_add'),
    path('comment/<int:id>/add/', views.add_comment, name='add_comment'),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils import timezone
from .managers import PostPublishedManager, PostManager
from rest_framework import serializers


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    text = models.TextField(verbose_name="Текст статьи")
    created_data = models.DateTimeField(default=timezone.now, verbose_name="Дата создания")
    published_date = models.DateTimeField(blank=True, null=True, verbose_name="Дата публикации")
    is_published = models.BooleanField(default=False, verbose_name="Запись опубликована?")
    objects = PostManager()
    published = PostPublishedManager()

    def is_publish(self):
       return True if self.published_date else False

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    class Meta:
        verbose_name = 'Запись в блоге'
        verbose_name_plural = 'Запись в блоге'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """
        Возвращает URL для просмотра полного текста поста.
        """
        return reverse('blog:post_detail', args=[str(self.id)])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField(verbose_name="Комментарий")
    created_data = models.DateTimeField(default=timezone.now, verbose_name="Дата создания")
    approved_comment = models.BooleanField(default=False, verbose_name="Одобрен?")

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

class CommentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Comment
        fields = ('created_date', 'text')

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'is_published')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

blog/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .forms import PostForm, CommentForm
from .models import Post, Comment


# Create your views here.
def post_list(request):
    posts = Post.objects.for_user(user=request.user)
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, id):
    post = get_object_or_404(Post, id=id)
    if not post.is_publish() and not request.user.is_staff:
        raise Http404("Запись в блоге не найдена")
    return render(request, 'blog/post_detail.html', {'post': post})

def handler404(request, exception, template_name="404.html"):
    response = render(request, "404.html")
    response.status_code = 404
    return response

def post_add(request):
   if request.user.is_authenticated:
       if request.method == "POST":
           form = PostForm(request.POST)
           if form.is_valid():
               post = form.save(commit=False)
               post.author = request.user
               post.published_date = timezone.now()
               post.save()
               return redirect('blog:post_detail', id=post.id)
       else:
               form = PostForm()
       return render(request, 'blog/post_edit.html', {'form': form})
   return redirect('post_list')

@login_required
def post_edit(request, id):
    post = get_object_or_404(Post, id=id) if id else None

    if post and post.author != request.user:
        return redirect('post_list')

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            if post.is_published:
                post.published_date = timezone.now()
            else:
                post.published_date = None
            post.save()
            return redirect('blog:post_detail', id=post.id)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})\

@login_required
def post_publish(request, id):
    post = get_object_or_404(Post, id=id)
    post.publish()
    return redirect('blog:post_detail', id=id)

def add_comment(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.created_date = timezone.now()
            comment.author = request.user
            comment.save()
            return redirect('blog:post_detail', id = post.id)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment.html', {'form': form})

blog/templates/blog/add_comment.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>Добавить комментарий</h2>
    <form method="post" class="comment-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>My first blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin.cyrillic" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'blog/css/theme.css' %}">
    </head>
    <body>
        {% block header %}
        <div class="page-header">
            {% if request.user.is_authenticated %}
                <a href="{% url 'logout' %}" class="top-menu"><span class="glyphicon glyphicon-log-out"></span>></a>
                <a href="{% url 'blog:post_add' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span>></a>
            {% else %}
                <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-log-in"></span>></a>
            {% endif %}
            <h1><a href="/">Home</a></h1>
        </div>
        {% endblock %}
        <div>
            <div class="content container">
                <div class="row">
                    <div class="col-md-8">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </body>
    
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="post">
        {% if post.published_date %}
        <div class="date">
            {{ post.published_date }}
        </div>
        {% else %}
            <a class="btn btn-default" href="{% url 'blog:post_publish' id=post.id %}">Опубликовать</a>
        {% endif %}
        {% if request.user == post.author %}
        <a class="btn btn-default" href="{% url 'blog:post_edit' id=post.id %}"><span class="glyphicon glyphicon-pencil"></span>></a>
        {% endif %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>

<hr>
<a class="btn btn-default" href="{% url 'blog:add_comment' id=post.id %}">Добавить комментарий</a>
{% for comment in post.comments.all %}
    <div class="comment">
        <div class="date">{{ comment.created_date }}</div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
{% empty %}
    <p>Комментарии осутствуют</p>
{% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% load widget_tweaks %}
{% block content %}
<h1>
    {% if form.instance.id %}
    Редактировать: {{ form.instance.title }}
    {% else %}
    Новая запись
    {% endif %}
</h1>

<form method="POST" class="post-form">
    {% csrf_token %}
    <div class="form-group">
        {{ form.title.label_tag }}
        {{ form.title|add_class:"form-control" }}
    </div>
    <div class="form-group">
        {{ form.text.label_tag }}
        {{ form.text|add_class:"form-control" }}
    </div>
    <div class="checkbox">
        <label>{{ form.is_published }}Запись опубликована?</label>
    </div>
    <button type="submit" class="save btn btn-default">Сохранить</button>
</form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
    <div class="post">
        <div class="date">
            <p>Дата публикации: {{ post.published_date }}</p>
            <p>Автор: {{ post.author }}</p>
        </div>
            <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}